### ISSUE TITLE
Dead lock when playing

### ISSUE THREAD

**Issue by pierrexn** [wang-bin/mdk-sdk#259] opened 2024-12-07 08:14 UTC
with 0.30.1, i have a dead lock when trying to play this file

https://github.com/user-attachments/assets/fd8ee035-3fbb-424f-b07b-6d1af1694e33

**Comment by wang-bin** [comment] 2024-12-08 14:08
Which platform? I need your log

**Comment by pierrexn** [comment] 2024-12-08 14:17
Sorry, Windows and here is the logs...
[logs.txt](https://github.com/user-attachments/files/18052585/logs.txt)

**Comment by wang-bin** [comment] 2024-12-09 05:49
try https://github.com/wang-bin/mdk-sdk/actions/runs/12229752213

please also check if #127 and #177 is not affected because i have no windows environment now

**Comment by pierrexn** [comment] 2024-12-09 12:52
same lock, and i have a crash when playing #127 & #177

**Comment by wang-bin** [comment] 2024-12-09 16:54
I guess the crash is in ffmpeg. download again and try again. show me the new log of this issue.

**Comment by wang-bin** [comment] 2024-12-10 14:28
I can reproduce the issue in a VM with latest mft hevc extension, should be fixed in this build https://github.com/wang-bin/mdk-sdk/actions/runs/12258197922

**Comment by pierrexn** [comment] 2024-12-10 15:28
It's fixed!

**Closed** 2024-12-10 16:25 UTC

**Comment by pierrexn** [comment] 2025-01-08 07:56
when do you think to release the fixed version?

**Comment by wang-bin** [comment] 2025-01-08 07:59
not sure, maybe next month, i'm busy recently
